name: Build Multienv Artifacts

on:
  push:

  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "all"
        type: choice
        options:
          - sit
          - qa
          - uat
          - all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-list: ${{ steps.set-build-list.outputs.list }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Determine build environments
        id: set-build-list
        shell: bash
        run: |
          ENV="${{ github.event.inputs.environment }}"
          ORDER=("sit" "qa" "uat")
          BUILD_LIST=()
          if [ "$ENV" = "all" ]; then
            BUILD_LIST=("${ORDER[@]}")
          else
            BUILD_LIST=("$ENV")
          fi
          echo "Environments to build: ${BUILD_LIST[@]}"
          echo "::set-output name=list::${BUILD_LIST[*]}"

      - name: Build & Publish for each environment
        shell: bash
        run: |
          BUILD_LIST=(${{ steps.set-build-list.outputs.list }})
          for e in "${BUILD_LIST[@]}"; do
            echo "=== Building $e ==="
            cd client
            npx ng build --configuration "$e"
            cd ..
            dotnet publish API/API.csproj -c Release -o "./publish-$e"
          done

      - name: Upload artifacts dynamically
        shell: bash
        run: |
          BUILD_LIST=(${{ steps.set-build-list.outputs.list }})
          for e in "${BUILD_LIST[@]}"; do
            echo "Uploading artifact for $e"
            gh workflow upload-artifact --name "app-$e" --path "./publish-$e"
          done
