name: Build Multienv Artifacts

on:
  #push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-list: ${{ steps.set-build-list.outputs.list }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Determine build environments
        id: set-build-list
        shell: bash
        run: |
          ORDER=("sit" "qa" "uat")
          BUILD_LIST=("${ORDER[@]}")
          echo "Environments to build: ${BUILD_LIST[@]}"
          echo "::set-output name=list::${BUILD_LIST[*]}"

      - name: Build & Publish for each environment
        shell: bash
        run: |
          BUILD_LIST=(${{ steps.set-build-list.outputs.list }})
          for e in "${BUILD_LIST[@]}"; do
            echo "=== Building $e ==="
            # Angular build
            cd client
            npm ci
            npx ng build --configuration "$e"
            cd ..
            # .NET publish
            dotnet publish API/API.csproj -c Release -o "./publish-$e"
          done

      - name: Upload SIT artifact
        if: contains(steps.set-build-list.outputs.list, 'sit')
        uses: actions/upload-artifact@v4
        with:
          name: app-sit
          path: ./publish-sit

      - name: Upload QA artifact
        if: contains(steps.set-build-list.outputs.list, 'qa')
        uses: actions/upload-artifact@v4
        with:
          name: app-qa
          path: ./publish-qa

      - name: Upload UAT artifact
        if: contains(steps.set-build-list.outputs.list, 'uat')
        uses: actions/upload-artifact@v4
        with:
          name: app-uat
          path: ./publish-uat
