name: Build & Deploy Multienv. Pipeline

on:
  push:

  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: "main"
      environment:
        required: true
        type: choice
        options:
          - sit
          - qa
          - uat

jobs:
  build:
   runs-on: ubuntu-latest
   permissions:
      contents: read 

   steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Angular cli
        run: npm install -g @angular/cli@20

      - name: Install deps and build angular app
        run: |
          cd client
          npm install
          ng build

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 'v9.0'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish/

  deploy-to-sit:
   if: github.event_name == 'push'
   needs: build
   runs-on: ubuntu-latest
   environment: SIT
   permissions:
      id-token: write
      contents: read
   steps:
   - name: Download artifact from build job
     uses: actions/download-artifact@v4
     with:
      name: .net-app
      path: publish
   - name: Deploy to app service
     uses: Azure/webapps-deploy@v3.0.6
     with:
      app-name: ${{ secrets.APP_SERVICE_NAME }}
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ./publish
      
  deploy-to-qa:
   if: github.event_name == 'push'
   needs: deploy-to-sit
   runs-on: ubuntu-latest
   environment: QA
   steps:
   - name: Download artifact from build job
     uses: actions/download-artifact@v4
     with:
      name: .net-app
      path: publish
   - name: Deploy to app service
     uses: Azure/webapps-deploy@v3.0.6
     with:
      app-name: ${{ secrets.APP_SERVICE_NAME }}
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ./publish

  deploy-to-uat:
   if: github.event_name == 'push'
   needs: deploy-to-qa
   runs-on: ubuntu-latest
   environment: UAT
   steps:
   - name: Download artifact from build job
     uses: actions/download-artifact@v4
     with:
      name: .net-app
      path: publish
   - name: Deploy to app service
     uses: Azure/webapps-deploy@v3.0.6
     with:
      app-name: ${{ secrets.APP_SERVICE_NAME }}
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ./publish

  manual-deploy:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: publish
    - name: Deploy to app service
      uses: Azure/webapps-deploy@v3.0.6
      with:
        app-name: ${{ secrets.APP_SERVICE_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
