name: Build & Deploy Multienv. Pipeline Updated

on:
  push:

  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Deployment mode'
        required: true
        type: choice
        options:
          - single
          - sequential
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - sit
          - qa
          - uat

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@20

      - name: Install dependencies and build Angular app
        run: |
          cd client
          npm install
          ng build

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish/

  # -------------------------
  # DEPLOY TO SIT
  # -------------------------
  deploy-to-sit:
    needs: build
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' &&
      ((github.event.inputs.deploy_mode == 'single' && github.event.inputs.environment == 'sit') ||
      (github.event.inputs.deploy_mode == 'sequential' && (github.event.inputs.environment == 'sit' || github.event.inputs.environment == 'qa' || github.event.inputs.environment == 'uat'))))
    runs-on: ubuntu-latest
    environment: SIT
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

  # -------------------------
  # DEPLOY TO QA
  # -------------------------
  deploy-to-qa:
    needs: [build, deploy-to-sit]
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' &&
      ((github.event.inputs.deploy_mode == 'single' && github.event.inputs.environment == 'qa') ||
      (github.event.inputs.deploy_mode == 'sequential' && (github.event.inputs.environment == 'qa' || github.event.inputs.environment == 'uat'))))
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

  # -------------------------
  # DEPLOY TO UAT
  # -------------------------
  deploy-to-uat:
    needs: [build, deploy-to-qa]
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' &&
      ((github.event.inputs.deploy_mode == 'single' && github.event.inputs.environment == 'uat') ||
      (github.event.inputs.deploy_mode == 'sequential' && github.event.inputs.environment == 'uat')))
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
