name: Build & Deploy Multienv Pipeline

on:
  push:

  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Deployment mode'
        required: true
        type: choice
        options:
          - single
          - sequential
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - sit
          - qa
          - uat

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install -g @angular/cli@20
      - run: |
          cd client
          npm install
          ng build

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - run: dotnet build --configuration Release
      - run: dotnet publish -c Release -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: publish/

  # --- SEQUENTIAL DEPLOYMENTS (for push and sequential mode) ---
  deploy-to-sit:
    needs: build
    runs-on: ubuntu-latest
    environment: SIT
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_mode == 'sequential')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

  deploy-to-qa:
    needs: [build, deploy-to-sit]
    runs-on: ubuntu-latest
    environment: QA
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_mode == 'sequential' &&
      (github.event.inputs.environment == 'qa' || github.event.inputs.environment == 'uat'))
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

  deploy-to-uat:
    needs: [build, deploy-to-qa]
    runs-on: ubuntu-latest
    environment: UAT
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_mode == 'sequential' &&
      github.event.inputs.environment == 'uat')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

  # --- SINGLE DEPLOYMENTS (no dependencies, for single mode only) ---
  deploy-single:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_mode == 'single'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: publish
      - name: Deploy to selected environment
        uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets[format('APP_SERVICE_NAME_{0}', github.event.inputs.environment | upper)] }}
          publish-profile: ${{ secrets[format('AZURE_WEBAPP_PUBLISH_PROFILE_{0}', github.event.inputs.environment | upper)] }}
          package: ./publish
